### ISSUE TITLE
运行后提示initialized，无后续响应

### ISSUE THREAD

**Issue by Xm798** [hgjazhgj/GenshinAutoFish#1]
**说明你发现的bug**  
运行后提示`initialized`，然后没有后续响应。
**复现步骤**  
运行原神，调游戏分辨率为1280*720，管理员身份运行GenshinAutoFish.exe，钓鱼，鱼咬钩，点一下鼠标左键收钩，双手离开键鼠，鱼脱钩跑了。
**期待的行为**
能够把鱼钓上来
**截图/日志**  
![image](https://user-images.githubusercontent.com/48074861/132318201-ac952c52-50e8-401e-8640-996b11419d1a.png)
**设备信息**  
Windows 11 专业工作站版 Insider Preview 22449.1000 amd64
双屏扩展显示
**其他**  
暂无

**Comment by hgjazhgj** [comment]
哦我更新日志里写了但是正文里没写...这就加上  
每当鱼即将咬钩时按一下键盘上的SCROLL LOCK(滚动锁定)键才会开始检测鱼上钩的提示
