### ISSUE TITLE
部分硬件可能存在兼容转型问题?存疑

### ISSUE THREAD

**Issue by Nigh** [hgjazhgj/GenshinAutoFish#10]
为了避免缩放造成的问题，现以`1280`x`720`分辨率进行测试。

![capture](https://user-images.githubusercontent.com/1407471/132863269-f72bfa1d-7a3c-4530-9a4e-448bd547a751.gif)
上图显示，脚本未能正确检测到钓鱼的进度条。

上图是在咬钩瞬间按下`ScrollLock`，以确保脚本有时间检测到文字。

如果先于上钩时间按下`ScrollLock`，则会直接触发左键从而脱钩。

**Comment by Nigh** [comment]
本来想自己摸一个的，看到有现成的就懒得动手了。虽然现在还用不了。提几点建议吧：
1. 常见分辨率每个使用独立的素材，避免缩放导致的问题。
2. 判断鱼上钩使用右下角的图标变化，更加准确，并且可以适配不同的界面语言。

通过右下图标来区分不同的状态应该足以实现全自动钓鱼了。平时也可以保持脚本常开了。

**Comment by hgjazhgj** [comment]
试一试运行脚本不按任何键,在游戏中手动钓鱼,并且在出现「鱼儿上钩了」提示时和钓鱼进度条走到差不多一半时各按一下PAUSE BREAK键吧,然后看看脚本目录中的截图内容是否正确
正确的截图应该长这样:
![image](https://user-images.githubusercontent.com/40085173/132866580-d9c5af6b-2975-468d-813b-71b40513b22e.png)

在发送截图的时候,除了遮挡uid以外,最好也遮住角色的血量

**Comment by Nigh** [comment]
报错。
```
❯ .\GenshinAutoFish.exe
v1.7.0
initialized
Traceback (most recent call last):
  File "main.py", line 128, in <module>
TypeError: save() missing 1 required positional argument: 'self'
Press any key to continue . . .
```

**Comment by hgjazhgj** [comment]
淦我少打一对括号

**Comment by hgjazhgj** [comment]
![image](https://user-images.githubusercontent.com/40085173/132867002-8b5923c8-e5f5-4fb9-8343-38846dc15a82.png)
我看你有运行源码的条件,把128行改成`Check().save()`

**Comment by Nigh** [comment]
![capture_2021-09-10_22 14 47](https://user-images.githubusercontent.com/1407471/132867645-5e4e8e63-5363-4d2d-9ced-fe9266caedff.png)
全部如上。都是纯白。

**Comment by hgjazhgj** [comment]
那问题就在这里了

**Comment by Nigh** [comment]
试了下，使用`PrintWindow`方法得到的是纯黑的Bitmap。

**Comment by Nigh** [comment]
```ahk
Gdip_BitmapFromHWND(hwnd)
{
	Ptr := A_PtrSize ? "UPtr" : "UInt"
	CreateRect( winRect, 0, 0, 0, 0 ) ;is 16 on both 32 and 64
	DllCall( "GetWindowRect", Ptr, hwnd, Ptr, &winRect )
	Width := NumGet(winRect, 8, "UInt") - NumGet(winRect, 0, "UInt")
	Height := NumGet(winRect, 12, "UInt") - NumGet(winRect, 4, "UInt")
	hbm := CreateDIBSection(Width, Height), hdc := CreateCompatibleDC(), obm := SelectObject(hdc, hbm)
	PrintWindow(hwnd, hdc)
	pBitmap := Gdip_CreateBitmapFromHBITMAP(hbm)
	SelectObject(hdc, obm), DeleteObject(hbm), DeleteDC(hdc)
	return pBitmap
}
```
如上方法能拿到正确的bitmap，供参考。

**Comment by Nigh** [comment]
你改下，分别输出4个通道，我来测试下？不会python的说。

**Comment by hgjazhgj** [comment]
```
import win32con,win32ui,win32gui,win32api,win32print
import numpy,cv2

hDesktopDC = win32gui.GetDC(0)
winScale = win32print.GetDeviceCaps(hDesktopDC, win32con.DESKTOPHORZRES) \
            / win32print.GetDeviceCaps(hDesktopDC, win32con.HORZRES)
win32gui.ReleaseDC(None, hDesktopDC)
    
def windowCapture(hWnd):
    return(lambda hWnd:
           (lambda width,height:
            (lambda hWndDC:
             (lambda mfcDC:
              (lambda memDC,bitMap:
               (bitMap.CreateCompatibleBitmap(mfcDC,width,height),
                memDC.SelectObject(bitMap),
                memDC.BitBlt((0, 0),(width,height),mfcDC,(0,0),win32con.SRCCOPY),
                numpy.frombuffer(bitMap.GetBitmapBits(True),dtype='uint8').reshape(height,width,4),
                win32gui.DeleteObject(bitMap.GetHandle()),
                memDC.DeleteDC(),
                mfcDC.DeleteDC(),
                win32gui.ReleaseDC(hWnd,hWndDC)
               )[3]
              )(mfcDC.CreateCompatibleDC(),win32ui.CreateBitmap())
             )(win32ui.CreateDCFromHandle(hWndDC))
            )(win32gui.GetDC(hWnd))
           )(*[round(i*winScale)for i in win32gui.GetClientRect(hWnd)[2:]])
          )(hWnd if hWnd else hDesktopWnd)

hWnd=win32gui.FindWindow('UnityWndClass','原神')

img = windowCapture(hWnd)
cv2.imshow('capture', cv2.resize(img, (640, 360)))
cv2.waitKey(0)
cv2.destroyAllWindows()
for i in range(4):
    print(i)
    cv2.imwrite(f'{i}.png',img[...,i])
```
这段程序会显示截到的图并分别将四个通道写入四个png

**Comment by Nigh** [comment]
![未标题-1](https://user-images.githubusercontent.com/1407471/132879862-730f18ad-ea6d-44f2-aaed-8fabf7767481.jpg)
四张图片如上。

**Comment by hgjazhgj** [comment]
我图像设置全部拉满,然后关垂直同步,关动态模糊

**Comment by Nigh** [comment]
各种组合都过了一遍，alpha通道都没有，应该与设置无关。可能是显卡差异吧。

**Comment by hgjazhgj** [comment]
您用的是什么显卡?
我的是2080super

**Comment by Nigh** [comment]
1060，反正有这个情况，也不能指望用alpha通道了。

**Comment by hgjazhgj** [comment]
我也在试  
发现画质全最低的情况下透明度的背景是白的
具体哪个选项还在看

**Comment by hgjazhgj** [comment]
懂了,抗锯齿要用SMAA

**Comment by Nigh** [comment]
都试过，SMAA也是一样的。

**Comment by hgjazhgj** [comment]
你的显卡驱动版本是多少  
群友反应原神对旧版显卡驱动支持不好

**Comment by QAQQL** [comment]
补充:
测试版本:
1.7.1
测试环境:
Win10 20H2 GTX1050Ti i7-8750H 

测试截图数据:
![图片](https://user-images.githubusercontent.com/51136763/132908939-68ae0a93-71a9-4be6-99a7-6a01d2212e05.png)
![图片](https://user-images.githubusercontent.com/51136763/132909115-0bdb5aae-dd76-4295-aadd-827c6abfea51.png)
![图片](https://user-images.githubusercontent.com/51136763/132909141-55cacb4b-68e0-4f46-aa8c-715c5b150ef5.png)
![图片](https://user-images.githubusercontent.com/51136763/132909160-d93d3cc9-2a03-4e13-a6a8-ba6849dd1727.png)
![图片](https://user-images.githubusercontent.com/51136763/132909178-e3bfbd2f-7c76-46bb-8553-eda5fc5bfbb4.png)
![图片](https://user-images.githubusercontent.com/51136763/132909252-b09c2a40-2203-46de-afd9-c977e2b76ca8.png)
![图片](https://user-images.githubusercontent.com/51136763/132909313-fa2d7ee7-b97b-497d-8675-01c3ff94363b.png)
![图片](https://user-images.githubusercontent.com/51136763/132909340-962fe415-8a27-4087-bc37-e782c872efd7.png)

**Comment by QAQQL** [comment]
补充四通道图:
![图片](https://user-images.githubusercontent.com/51136763/132909750-b5da43ff-8f2d-44ef-b922-6af2e1ab0d2f.png)
![图片](https://user-images.githubusercontent.com/51136763/132909791-ab1887e2-8086-4242-883c-21089e8b0699.png)
![图片](https://user-images.githubusercontent.com/51136763/132909817-6f4e35f2-3907-436f-844d-304e61df4673.png)
![图片](https://user-images.githubusercontent.com/51136763/132909852-2b274225-97f5-4662-b3ba-6a8aa74f6218.png)

**Comment by QAQQL** [comment]
测试视频:
![TEST~2](https://user-images.githubusercontent.com/51136763/132912570-0136c753-9f6a-42ac-aa6d-ccea5d5a9824.gif)

**Comment by hgjazhgj** [comment]
@QAQQL  你的这个问题跟楼主遇到的不一样,你应该只要把抗锯齿算法改成SMAA就行了

**Comment by Nigh** [comment]
> 你的显卡驱动版本是多少
> 群友反应原神对旧版显卡驱动支持不好

```
操作系统：	Windows 10 Pro, 64-bit
DirectX 版本：	12.0 
GPU 处理器：		NVIDIA GeForce GTX 1060 3GB
驱动程序版本：			466.77
驱动器类型：			DCH
Direct3D 功能级别：		12_1
CUDA 核心：		1152 
核心时钟：			1544 MHz 
内存数据速率：			8.01 Gbps
内存接口：			192-位 
内存带宽：			192.19 GB/秒
全部可用的图形内存：		11238MB
专用视频内存：			3072 MB GDDR5
系统视频内存：			0MB
共享系统内存：			8166MB
视频 BIOS 版本：		86.06.59.00.47
IRQ：			Not used
总线：			PCI Express x16 Gen3
设备 ID：			10DE 1C02 85B31043
部件编号：			G410 0020
```

**Comment by Nigh** [comment]
> 你的显卡驱动版本是多少
> 群友反应原神对旧版显卡驱动支持不好

```
操作系统：	Windows 10 Pro, 64-bit
DirectX 版本：	12.0 
GPU 处理器：		NVIDIA GeForce GTX 1060 3GB
驱动程序版本：			466.77
驱动器类型：			DCH
Direct3D 功能级别：		12_1
CUDA 核心：		1152 
核心时钟：			1544 MHz 
内存数据速率：			8.01 Gbps
内存接口：			192-位 
内存带宽：			192.19 GB/秒
全部可用的图形内存：		11238MB
专用视频内存：			3072 MB GDDR5
系统视频内存：			0MB
共享系统内存：			8166MB
视频 BIOS 版本：		86.06.59.00.47
IRQ：			Not used
总线：			PCI Express x16 Gen3
设备 ID：			10DE 1C02 85B31043
部件编号：			G410 0020
```

**Comment by Nigh** [comment]
更新驱动至 `471.96` 现象一致。

**Comment by QAQQL** [comment]
> @QAQQL 你的这个问题跟楼主遇到的不一样,你应该只要把抗锯齿算法改成SMAA就行了

调整后已成功

**Comment by Mufanc** [comment]
还能用 alpha 通道！学到了，这就去改（

**Comment by hgjazhgj** [comment]
> 还能用 alpha 通道！学到了，这就去改（

窃码不能算偷...窃码!...程序员的事,能算偷吗!

**Comment by Mufanc** [comment]
![image](https://user-images.githubusercontent.com/47652878/132941111-5fe6be6c-c9b1-4346-af26-33aac7375581.png)
《我这通道怎么和你的不一样啊》

**Comment by Mufanc** [comment]
截图得到 RGBA 后 imshow 是正常样式，imwrite 再打开来看就只剩 ui 了（惊），抗锯齿是 SMAA

**Comment by hgjazhgj** [comment]
@Nigh 根据楼上的想法我写了个新版,你看看你能不能用?
注意由于你实际上并没有有效的透明度通道,建议游戏画面背景不要太亮

**Comment by Nigh** [comment]
勉强能用，亮色背景就会GG，需要及时的手动把视角转到暗点的方向。希望能加上通过右下图标判断状态的方式。可以免去手动按键的烦恼。

**Comment by yzjmxy** [comment]
> 勉强能用，亮色背景就会GG，需要及时的手动把视角转到暗点的方向。希望能加上通过右下图标判断状态的方式。可以免去手动按键的烦恼。

方便做个测试吗？

**Comment by yzjmxy** [comment]
> 勉强能用，亮色背景就会GG，需要及时的手动把视角转到暗点的方向。希望能加上通过右下图标判断状态的方式。可以免去手动按键的烦恼。

下载ddu，进入安全模式完全卸载显卡驱动

**Comment by yzjmxy** [comment]
> 勉强能用，亮色背景就会GG，需要及时的手动把视角转到暗点的方向。希望能加上通过右下图标判断状态的方式。可以免去手动按键的烦恼。

方便做个测试吗？
下载ddu，并进入安全模式打开ddu完全卸载清除显卡驱动。
并重新安装我提供的驱动文件。
https://wws.lanzoui.com/iGnTatwtghi
http://cn.download.nvidia.com/Windows/460.89/460.89-desktop-win10-64bit-international-whql.exe
这是ddu与显卡驱动的下载地址。

之后再使用1.7版本辅助程序进行测试  看看是否可行。
当然这只是一种个人猜测，再某种情况下可能会导致显卡的阿尔法通道出现错误。
毕竟在1050的显卡前提下的我都能正常使用，正常的话不可能出现1060无法使用的情况。

**Comment by hgjazhgj** [comment]
@yzjmxy 事实上我有几个群友也是1060，都是能用的
