### ISSUE TITLE
关于 Alpha 蒙版的几点建议

### ISSUE THREAD

**Issue by Mufanc** [hgjazhgj/GenshinAutoFish#12]
* 在某些性能不太好的 CPU 上，下面这段函数确实有点慢：
```python
def wrapAlpha(self, im):
        im = im.astype(numpy.uint16)
        alpha = im[..., 3]
        for i in range(3):
            im[..., i] *= alpha
        return (im//255)[..., :3].astype(numpy.uint8)
```

我的电脑 CPU 是 i7-10750H，再加上放在笔记本上没法跑满性能，这时候处理的速度就不太够了，建议使用如下优化：
```python
# bgra 是截图来的
img, alpha = bgra[..., :3] >> 4, bgra[..., 3] >> 4
for ch in range(3):
    np.multiply(img[..., ch], alpha, out=img[..., ch])
```
除 255 和除 256 实际区别并不大，稍改一下就能够省去类型转换的过程并原地进行处理，实测在效率上有较大的提升

**Comment by hgjazhgj** [comment]
这个看起来确实很快!
除以 255 和除以 256 的区别其实有点大,先分别位移再乘起来似乎也会有误差?  
但是我会考虑以此算法处理图像后重新制作模板,都有误差就是没有误差  
另外,`np.multiply`和`np.ndarray.__imul__`有效率上的区别吗,没写过需要这样死抠性能的代码不是很了解他们的区别...

**Comment by Mufanc** [comment]
这个快速算法处理的图片用 imshow 展示出来确实会有一些误差，不过完全在可接受范围内。另外我也不是很了解 np.multiply 和 __imul__ 的内部实现，但是感觉上 np.multiply 会快一些（？）

**Comment by hgjazhgj** [comment]
由于现在我只会对即将被识别的区域进行透明度混合,所以`np.multiply`和`np.ndarray.__imul__`都要不了1ms时间,就不详细测试了
