### ISSUE TITLE
关于21:9屏幕比例下无法识别到鱼儿上钩的问题

### ISSUE THREAD

**Issue by YouKnowMyEggs** [hgjazhgj/GenshinAutoFish#13]
屏幕比例21:9；分辨率2560*1080全屏无边框，无法识别到「**鱼儿上钩了**」，程序一直处于wait状态。V1.8.1版本及其之前的版本一切正常。
![QQ图片20210913161337](https://user-images.githubusercontent.com/18475010/133049061-acbb0469-3cb5-4a85-87dd-c4c117fb7af8.png)

**Comment by hgjazhgj** [comment]
我看看...
现在识别的不是「鱼儿上钩了」,而是右下角的鱼竿图标

**Comment by hgjazhgj** [comment]
卧槽我发现了原神的bug!
在我测试全分辨率适配的时候,我总是先以16:9启动(因为我自己玩的时候全屏就是16:9),然后随机从游戏分辨率表中挑选一个幸运分辨率  
在这种情形下,各识别目标相对边框的距离比例是不变的  
然而你的2160x1080并不在我的分辨率列表里面,所以我**先关闭游戏,然后改注册表,再开游戏**  
这样一来,21:9的屏幕就在左右两侧多出了一个偏移  
同样地,在游戏中更改完分辨率然后重启也有相同表现  
也就是说,原神的热更改分辨率有bug!  
我会在后续更新中扩大识别范围

**Comment by hgjazhgj** [comment]
那么,为什么1.8.1及之前的版本是正常的呢?  
因为那时候匹配「鱼儿上钩了」,这个提示在更改分辨率后的位置比例是不变的

**Comment by YouKnowMyEggs** [comment]
是的，而且是1.0就存在的BUG，我在游戏内选16:9的分辨率会导致我背包物品栏显示不完全（重合），直到现在这个问题都没修复，主要是每次钓鱼我要改比例重启游戏就很麻烦，所以直接提issue了233333
