### ISSUE TITLE
关于21:9屏幕比例下钓鱼总是失败的问题

### ISSUE THREAD

**Issue by YouKnowMyEggs** [hgjazhgj/GenshinAutoFish#14]
V2.1.1版本在21:9的屏幕比例2560*1080分辨率下能识别鱼竿并且自动收杆，但浮漂要么在进度条左侧一动不动，要么上来就直接顶到进度条右侧导致钓鱼必定失败。钓鱼失败后程序返回Traceback如下：
Traceback (most recent call last):
  File "main.py", line 139, in <module>
ValueError: '=' alignment not allowed in string format specifier
![1](https://user-images.githubusercontent.com/18475010/133106713-a290aa91-52aa-40b2-b2c3-29a677cd0470.png)
![2](https://user-images.githubusercontent.com/18475010/133109119-1f2ca356-1460-437d-a4c8-db9fc2890bd7.png)

**Comment by hgjazhgj** [comment]
出这个错的直接原因是识别的张力区间的开始位置==结束位置  
当然我自己测试是没问题的....我们的张力条位置是不是不一样?
![image](https://user-images.githubusercontent.com/40085173/133111961-9976bd37-7216-4e6a-bac4-ed343ab7d1d1.png)

**Comment by hgjazhgj** [comment]
贴出你的游戏内画面设置

**Comment by YouKnowMyEggs** [comment]
![1](https://user-images.githubusercontent.com/18475010/133115851-3d83f499-c636-4d4b-82cc-17bb4b83dac9.png)
![2](https://user-images.githubusercontent.com/18475010/133115875-606461c3-8945-4b1c-bab1-b47b0308bf02.png)

**Comment by YouKnowMyEggs** [comment]
@hgjazhgj 你的进度条相对我的进度条向下偏移了73个像素点的样子，其他UI都对得上。
![3](https://user-images.githubusercontent.com/18475010/133120249-3f1dcb9a-35f5-41ea-850a-03c92e27e552.png)

**Comment by hgjazhgj** [comment]
将画面高度映射到720后张力区间框顶端到画面顶端的距离是多少

**Comment by hgjazhgj** [comment]
目前我只知道back//10-front//10-1==0
实在是想不到有什么情况会这样
你试着将config.json中的startKey改为145然后手动钓一次鱼,并在钓鱼过程中按住PAUSE BREAK键,将脚本目录下的截图挑一张发给我
用色块遮盖个人信息,不要裁剪或模糊

**Comment by YouKnowMyEggs** [comment]
> 将画面高度映射到720后张力区间框顶端到画面顶端的距离是多少

52个像素点

**Comment by YouKnowMyEggs** [comment]
> 目前我只知道back//10-front//10-1==0
> 实在是想不到有什么情况会这样
> 你试着将config.json中的startKey改为145然后手动钓一次鱼,并在钓鱼拉扯过程中按一下PAUSE BREAK键,将脚本目录下的截图发给我
> 用色块遮盖个人信息,不要裁剪或模糊

![3](https://user-images.githubusercontent.com/18475010/133122148-2377e1d0-e735-4f17-8ec2-c21af8a97b5c.png)

**Comment by hgjazhgj** [comment]
这张力条和顶端也靠得太近了...真不知道mhy的布局算法怎么写的...还人人不一样...  
游标停在左边可以理解,因为检测不到光标所以不会拉扯,这会在明天的更新中予以修正  
但是游标停在右边和那个报错又是怎么回事呢...

**Comment by hgjazhgj** [comment]
刚push了2.1.2,你看看能不能跑,会报什么错吧...

**Comment by YouKnowMyEggs** [comment]
> 刚push了2.1.2,你看看能不能跑,会报什么错吧...

没有问题了，完美！
