### ISSUE TITLE
修改StartKey后无法启动

### ISSUE THREAD

**Issue by Xm798** [hgjazhgj/GenshinAutoFish#15]
**说明你发现的bug**  
修改StartKey后无法启动。

**复现步骤**  
修改配置文件中`"startKey"`为145或其他按键，程序无法运行。

**截图/日志**  
![image](https://user-images.githubusercontent.com/48074861/133620915-204b08c0-5cbb-4f0e-a7d2-df341dc0ca64.png)

**Comment by hgjazhgj** [comment]
哦这显然是我startKey错拼成了startKwy...
不多于三个字的英文字符不会被拼写检查...而我自己调试用的是另一个config文件...
