### ISSUE TITLE
关于SCROLL LOCK键在笔记本电脑上没有的问题

### ISSUE THREAD

**Issue by QAQQL** [hgjazhgj/GenshinAutoFish#2]
**笔记本电脑上没有SCROLL LOCK键,望作者更换一下**  
下载源码编译时报cv错误,如果作者不忙的话麻烦告知一下opencv版本
![图片](https://user-images.githubusercontent.com/51136763/132333556-8f4155ec-a7ad-4c19-8876-5c7545e08dd3.png)

**Comment by hgjazhgj** [comment]
SCROLL LOCK键的系列问题会在下个更新中解决  
本项目的release是由GitHub Action自动打包发布的,此时的opencv版本应该就是对应python环境(3.9)下可用的最新版本
在我自己的电脑上,是python 3.9和opencv-python 4.5.3.56

**Comment by QAQQL** [comment]
谢谢,已成功搭建,就是初始时如果框往右边时,算法会多点一次导致右飘有点远,可能需要优化一下
