### ISSUE TITLE
关于脚本改进的建议

### ISSUE THREAD

**Issue by ll789899** [hgjazhgj/GenshinAutoFish#3]
1.希望可以通过识别 “鱼儿上钩了” 的提示文字 来进行自动收杆
2.关于背景导致的识别问题 可以在收杆时（视角会自动回正）自动下拉鼠标 让视角正对脚底 只要此时识别区域不是正对白色地板就没问题（这个其实在一开始调整好站位就行）

**Comment by hgjazhgj** [comment]
1. 这个脚本从最初的commit就是根据识别「鱼儿上钩了」文字来自动收杆的  
2. 这个考虑做
