### ISSUE TITLE
关于钓鱼点击的一些建议

### ISSUE THREAD

**Issue by QAQQL** [hgjazhgj/GenshinAutoFish#4]
While(Ture)的间隔过短,识别频率过高导致点击的次数过多使浮标经常超出钓鱼框,加了一小段延时后改善效果明显
修改如下:
if cur + 5 < (back + front) // 2:
                window.click(.1)
                time.sleep(.1)

望作者测试一下

**Comment by hgjazhgj** [comment]
这个我觉得是不会的,本身拉杆的逻辑就是如果光标落后区间中点5px就按0.1秒鼠标  
如果你那里经常游标靠右超出最佳张力框,应该试着把0.1秒改小而不是在其后增加延时
