### ISSUE TITLE
打开 软件之后，无响应

### ISSUE THREAD

**Issue by tootony** [hgjazhgj/GenshinAutoFish#5]
出现cmd指令后立刻消失了，是不是启动成功了

**Comment by hgjazhgj** [comment]
不是  
在管理员命令行中运行查看输出,贴在这里

**Comment by crassing** [comment]
我也是，管理员打开以后命令行窗口一闪而过，然后就没了...

**Comment by hgjazhgj** [comment]
> 我也是，管理员打开以后命令行窗口一闪而过，然后就没了...
> 是不是我电脑上安有python的原因？那个版本是3.8的

闪退的倒是把闪退前的输出贴上来啊  
打包好的可执行文件不会和本地的python冲突  
另外有python的直接运行源码不就行了

**Comment by crassing** [comment]
![Uploading 1.gif…]()
![Uploading 屏幕截图 2021-09-08 184554.png…]()
这样子的

**Comment by hgjazhgj** [comment]
哦淦我打包文件写错了,config.json被放进了config.json/config.json里面..........
这就改

**Comment by tootony** [comment]
谢谢 作者
