### ISSUE TITLE
新版本不识别鱼上钩

### ISSUE THREAD

**Issue by QAQQL** [hgjazhgj/GenshinAutoFish#9]
**last版本已无法识别鱼是否上钩,直接点击收竿**  
测试时间:
2021年9月10日11:17:04
测试界面:
![图片](https://user-images.githubusercontent.com/51136763/132793994-edcdcba3-db9c-4caf-80f5-6b4c9229431e.png)
测试分辨率:
1600*900
经多个版本测试,疑似图色错误

**Comment by hgjazhgj** [comment]
我自己在相同分辨率下测是没问题的,请提供具体复现步骤  
另:对于活动钓鱼挑战,请下载1.7.0及之后的版本

**Comment by YlovexLN** [comment]
是不是因为鱼咬钩了，不是马上按收杆的原因。因为我是1920:1080 全屏无边框的，有几次没注意收杆，按慢了脚本就没有反应。

**Comment by YlovexLN** [comment]
> 是不是因为鱼咬钩了，不是马上按收杆的原因。因为我是1920:1080 全屏无边框的，有几次没注意收杆，按慢了脚本就没有反应。

经过多次测试，鱼咬钩3秒不按的话就会失效，当再一次抛竿鱼咬钩就会自动收杆不需要去按激活键。

**Comment by hgjazhgj** [comment]
> > 是不是因为鱼咬钩了，不是马上按收杆的原因。因为我是1920:1080 全屏无边框的，有几次没注意收杆，按慢了脚本就没有反应。
> 
> 经过多次测试，鱼咬钩3秒不按的话就会失效，当再一次抛竿鱼咬钩就会自动收杆不需要去按激活键。

你应该在抛竿后鱼朝着饵游过来的时候(**开始吃饵即将咬钩时**)就按键...  
我会在按键后检测鱼什么时候咬钩,你等鱼已经咬钩后几秒再按键提示文字消失了当然检测不到,直到下一次出现提示文字才会自动收杆

**Comment by Nigh** [comment]
![20210910204814](https://user-images.githubusercontent.com/1407471/132859263-22129111-d8be-439c-85fb-dbb366657c45.png)
图中命令行窗口显示检测位置无效。脚本与二进制测试现象一致。

窗口为`1920x1080`无边框

## 重现

### 操作流程一：
1. 管理员权限启动脚本
2. 甩杆
3. 鱼将要咬钩时按下`Scroll Lock`

按下按键的同时，就触发了脚本点击左键，直接收杆了。

### 操作流程二：
1. 管理员权限启动脚本
2. 甩杆
3. 鱼咬钩瞬间按下`Scroll Lock`

如截图所示，脚本无动作，其中左边为手动操作。

**Comment by hgjazhgj** [comment]
奇怪,很jb奇怪  
首先能够实现收杆说明模拟鼠标输入是有效的
想要触发任何输入首先得检测到「鱼儿上钩了」提示,先不论识别对不对,至少截图是能截到的  
输入输出都有那么就是我算法的问题咯?可是又有那么多人能用  

先姑且试一试运行脚本不按任何键,在游戏中手动钓鱼,并且在**出现「鱼儿上钩了」提示时**和**钓鱼进度条走到差不多一半时**各按一下PAUSE BREAK键吧,然后看看脚本目录中的截图内容是否正确  
正确的截图应该长这样:  
![image](https://user-images.githubusercontent.com/40085173/132865516-f91f2853-8a19-49f9-aee2-8d7c4d3cbef5.png)
在发送截图的时候,除了遮挡uid以外,最好也遮住角色的血量

**Comment by hgjazhgj** [comment]
@QAQQL  你看看你的抗锯齿算法是否是SMAA
